/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.awt.List;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.Map;

/**
 *
 * @author mariamsameh
 */
public class NewJFrame extends javax.swing.JFrame {
    private JTable productTable;
    private JTextField productNameField, productQuantityField;
    private JButton addProductButton, printInventoryButton;
    private JButton addSupplierButton, generateReportButton;
  
    
   
    public NewJFrame() {
    
       
        setTitle("Inventory Management System");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(null);

        JLabel titleLabel = new JLabel("Inventory Management System");
        titleLabel.setBounds(250, 10, 300, 30);
        add(titleLabel);

        // Product Table
        String[] columns = {"Product Name", "Quantity"};
        DefaultTableModel tableModel = new DefaultTableModel(columns, 0);
        productTable = new JTable(tableModel);
        JScrollPane scrollPane = new JScrollPane(productTable);
        scrollPane.setBounds(50, 50, 700, 300);
        add(scrollPane);
 // Input Fields
        JLabel nameLabel = new JLabel("Product Name:");
        nameLabel.setBounds(50, 370, 100, 25);
        add(nameLabel);

        productNameField = new JTextField();
        productNameField.setBounds(150, 370, 150, 25);
        add(productNameField);

        JLabel quantityLabel = new JLabel("Quantity:");
        quantityLabel.setBounds(50, 410, 100, 25);
        add(quantityLabel);

        productQuantityField = new JTextField();
        productQuantityField.setBounds(150, 410, 150, 25);
        add(productQuantityField);

        // Buttons for Inventory
        addProductButton = new JButton("Add Product");
        addProductButton.setBounds(50, 450, 150, 30);
        add(addProductButton);

        printInventoryButton = new JButton("Print Inventory");
        printInventoryButton.setBounds(220, 450, 150, 30);
        add(printInventoryButton);
        // Buttons
        addSupplierButton = new JButton("Add Supplier");
        addSupplierButton.setBounds(390, 450, 150, 30);
        add(addSupplierButton);
        addSupplierButton.addActionListener(e -> openAddSupplierScreen());
        generateReportButton = new JButton("Generate Report");
        generateReportButton.setBounds(560, 450, 150, 30);
        add(generateReportButton);
       generateReportButton.addActionListener(e -> openGenerateReportScreen());
        // Button Actions
        addProductButton.addActionListener(e -> addProduct());
        printInventoryButton.addActionListener(e -> printInventory());
        addSupplierButton.addActionListener(e -> openAddSupplierScreen());
        generateReportButton.addActionListener(e -> openGenerateReportScreen());
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inventory Management System");

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Add Supplier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Generate Report");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(83, 83, 83))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(153, 153, 153)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(47, 47, 47)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(47, 47, 47))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 0, 530, 487);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JButton addSupplierButton = new JButton("Add Supplier");
        addSupplierButton.setBounds(250, 400, 150, 30);
        add(addSupplierButton);
        addSupplierButton.addActionListener(e -> openAddSupplierScreen());
        
         generateReportButton.addActionListener(e -> openGenerateReportScreen());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       addSupplierButton.addActionListener(e -> openAddSupplierScreen());
       generateReportButton.addActionListener(e -> openGenerateReportScreen());
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */SwingUtilities.invokeLater(() -> new NewJFrame().setVisible(true));
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       SwingUtilities.invokeLater(() -> {
                new NewJFrame().setVisible(true);
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

     // Add Product to Inventory
    private void addProduct() {
        String productName = productNameField.getText();
        String quantityText = productQuantityField.getText();

        if (productName.isEmpty() || quantityText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both product name and quantity.");
            return;
        }

        try {
            int quantity = Integer.parseInt(quantityText);
            InventoryManager.getInstance().addProduct(productName, quantity);
            updateTable();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Quantity must be a valid number.");
        }
    }

    // Print Inventory
    private void printInventory() {
        InventoryManager.getInstance().printInventory();
    }

    // Update Table
    private void updateTable() {
        DefaultTableModel tableModel = (DefaultTableModel) productTable.getModel();
        tableModel.setRowCount(0); // Clear table

        for (Map.Entry<String, Integer> entry : InventoryManager.getInstance().inventory.entrySet()) {
            tableModel.addRow(new Object[]{entry.getKey(), entry.getValue()});
        }
    }

private void openAddSupplierScreen() {
    // استخدام Adapter
    LegacySupplier legacySupplier = new LegacySupplier();
    Supplier adapter = new LegacySupplierAdapter(legacySupplier);

    // إضافة المورد باستخدام Adapter
    adapter.addSupplier("Mariam Electronics", "Local Supplier");
    JOptionPane.showMessageDialog(this, "Supplier added using Adapter Pattern!");

    // استخدام Builder
     SupplierBuilder supplier = new SupplierBuilder.Builder()
                        .setName("Global Electronics")
                        .setType("International")
                        .setContactNumber("123-456-7890")
                        .build();

    // عرض معلومات المورد باستخدام Builder
    supplier.displaySupplier();
    JOptionPane.showMessageDialog(this, "Supplier added using Builder Pattern!");
}


 // Open Generate Report Screen
    private void openGenerateReportScreen() {
        new GenerateReportScreen().setVisible(true);
         StringBuilder report = new StringBuilder("Inventory Report:\n");
        DefaultTableModel productModel = (DefaultTableModel) productTable.getModel();

        for (int i = 0; i < productModel.getRowCount(); i++) {
            report.append("Product: ").append(productModel.getValueAt(i, 0))
                    .append(", Quantity: ").append(productModel.getValueAt(i, 1)).append("\n");
        }

    
        JTextArea reportArea = new JTextArea(report.toString());
        reportArea.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(reportArea);
        JOptionPane.showMessageDialog(this, scrollPane, "Generated Report", JOptionPane.INFORMATION_MESSAGE);
    
    }



       
    }

